import garageLogoNavy from "../assets/icons/garage-logo-navy.svg";
import { useState, useMemo } from "react";
import Sidebar from "../components/Sidebar.jsx"
import {
  Gauge, Wrench, Car, Users, Package, ClipboardList, Settings, LifeBuoy,
  Search, Bell, ChevronDown, Download, Eye, Trash2, ArrowUp, ArrowDown,
  Calendar, FileDown, ArrowRight, ChevronRight, PlusCircle, FileBarChart,
  FileText, Filter, Repeat2, Layers
} from "lucide-react";
import {
  AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  BarChart, Bar, PieChart, Pie, Cell
} from "recharts";

/* ---------------- data ---------------- */

const STATUS = [
  { label: "Completed", value: 82, pct: 64.1, color: "var(--green)" },
  { label: "In Progress", value: 28, pct: 21.9, color: "var(--steel-light)" },
  { label: "Pending", value: 34, pct: 26.6, color: "var(--amber)" },
  { label: "Waiting Parts", value: 12, pct: 9.4, color: "var(--rust)" },
  { label: "Cancelled", value: 4, pct: 3.1, color: "var(--red)" },
];

const CATEGORIES = [
  { name: "General Service", value: 45, pct: 35.2 },
  { name: "Brake Repair", value: 28, pct: 21.9 },
  { name: "Engine Repair", value: 22, pct: 17.2 },
  { name: "AC Service", value: 18, pct: 14.1 },
  { name: "Oil Change", value: 13, pct: 10.2 },
];

const MECHANICS = [
  { name: "Kasun Silva", completed: 18, pending: 4, rating: 4.8 },
  { name: "Nimal Fernando", completed: 15, pending: 3, rating: 4.6 },
  { name: "Priyantha", completed: 14, pending: 5, rating: 4.5 },
  { name: "Nalinda", completed: 12, pending: 2, rating: 4.3 },
  { name: "Chaminda", completed: 8, pending: 4, rating: 4.1 },
];

const REPORTS = [
  { id: "WO-2201", name: "Daily Service Report", type: "Daily", range: "May 27, 2025", by: "John Perera", fmt: "PDF" },
  { id: "WO-2198", name: "Weekly Performance Report", type: "Weekly", range: "May 20 – 27, 2025", by: "John Perera", fmt: "PDF" },
  { id: "WO-2190", name: "Mechanic Performance Report", type: "Mechanic", range: "May 01 – 27, 2025", by: "John Perera", fmt: "XLS" },
  { id: "WO-2187", name: "Monthly Revenue Report", type: "Financial", range: "May 01 – 27, 2025", by: "John Perera", fmt: "PDF" },
  { id: "WO-2179", name: "Service Summary Report", type: "Service", range: "May 20 – 27, 2025", by: "John Perera", fmt: "PDF" },
];

/* ---------------- helpers ---------------- */

function seededValue(seed, min, max) {
  let hash = 0;
  for (let i = 0; i < seed.length; i++) hash = (hash * 31 + seed.charCodeAt(i)) >>> 0;
  return min + (hash % (max - min + 1));
}

const DAY_LABELS = ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"];

function generateTrend(fromStr, toStr) {
  const from = new Date(fromStr);
  const to = new Date(toStr);
  if (isNaN(from) || isNaN(to) || from > to) return [];
  const out = [];
  const cursor = new Date(from);
  let guard = 0;
  while (cursor <= to && guard < 31) {
    const iso = cursor.toISOString().slice(0, 10);
    out.push({
      date: iso,
      day: DAY_LABELS[cursor.getDay()] + " " + cursor.getDate(),
      jobs: seededValue(iso + "j", 4, 28),
      revenue: seededValue(iso + "r", 20, 130),
    });
    cursor.setDate(cursor.getDate() + 1);
    guard++;
  }
  return out;
}

function downloadCSV(trend, kpis, reports) {
  const lines = [
    ["AutoCare Garage - Supervisor Report"],
    [],
    ["Metric", "Value"],
    ...kpis.map((k) => [k.label, k.value]),
    [],
    ["Day", "Jobs", "Revenue (Rs '000)"],
    ...trend.map((t) => [t.day, t.jobs, t.revenue]),
    [],
    ["Report ID", "Name", "Type", "Date Range", "Generated By", "Format"],
    ...reports.map((r) => [r.id, r.name, r.type, r.range, r.by, r.fmt]),
  ];
  const csv = lines.map((row) => row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(",")).join("\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "autocare-dashboard.csv";
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

/* ---------------- styles ---------------- */




/* ---------------- gauge helper ---------------- */

function Gauge_({ pct, color, value, delta, positive }) {
  const bg = `conic-gradient(${color} ${pct * 3.6}deg, var(--panel-alt) 0deg)`;
  return (
    <div className="gd-gauge-ring" style={{ background: bg }}>
      <span className="gd-gauge-val">{pct}%</span>
    </div>
  );
}

/* ---------------- app ---------------- */

export default function ReportGeneration() {
  const [dateFrom, setDateFrom] = useState("2025-05-20");
  const [dateTo, setDateTo] = useState("2025-05-27");
  const [exportOpen, setExportOpen] = useState(false);

  const trend = useMemo(() => generateTrend(dateFrom, dateTo), [dateFrom, dateTo]);

  const kpis = useMemo(() => {
    const totalJobs = trend.reduce((s, t) => s + t.jobs, 0) || 1;
    const completed = Math.round(totalJobs * 0.64);
    const pending = Math.round(totalJobs * 0.27);
    const customers = Math.round(totalJobs * 0.75);
    return [
      { label: "Total Jobs", value: String(totalJobs), pct: 100, color: "var(--steel-light)", delta: "+12.5%", positive: true },
      { label: "Completed", value: String(completed), pct: Math.round((completed / totalJobs) * 100), color: "var(--green)", delta: "+18.3%", positive: true },
      { label: "Pending", value: String(pending), pct: Math.round((pending / totalJobs) * 100), color: "var(--amber)", delta: "-6.7%", positive: false },
      { label: "Customers", value: String(customers), pct: 78, color: "var(--rust)", delta: "+15.7%", positive: true },
    ];
  }, [trend]);

  const handlePrint = () => {
  setExportOpen(false);
  window.dispatchEvent(new Event("resize"));
  setTimeout(() => window.print(), 200);
};
  const handleCsv = () => {
    setExportOpen(false);
    downloadCSV(trend, kpis, REPORTS);
  };

  return (
    
      <main className="main-panel gd-root">
        <img src={garageLogoNavy} alt="JAG" className="gd-print-logo" />

        <div className="gd-body">
          <div className="gd-toolbar">
            <div className="gd-range">
              <Calendar size={13} />
              <input type="date" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} max={dateTo} />
              <span className="gd-range-sep">–</span>
              <input type="date" value={dateTo} onChange={(e) => setDateTo(e.target.value)} min={dateFrom} />
            </div>
            <div className="gd-export-wrap">
              <button className="gd-export" onClick={() => setExportOpen((v) => !v)}>
                <FileDown size={14} /> Export Dashboard <ChevronDown size={13} />
              </button>
              {exportOpen && (
                <div className="gd-export-menu">
                  <div className="gd-export-item" onClick={handlePrint}><FileDown size={14} /> Export as PDF</div>
                  <div className="gd-export-item" onClick={handleCsv}><Download size={14} /> Export as CSV</div>
                </div>
              )}
            </div>
          </div>

          <div className="gd-layout">
            <div className="gd-content">
              <div className="gd-gauges">
                {kpis.map((k) => (
                  <div className="gd-gauge-card" key={k.label}>
                    <Gauge_ {...k} />
                    <div>
                      <div className="gd-gauge-label">{k.label}</div>
                      <div className="gd-gauge-num gd-mono">{k.value}</div>
                      <div className={"gd-gauge-delta " + (k.positive ? "gd-up" : "gd-down")}>
                        {k.positive ? <ArrowUp size={11} /> : <ArrowDown size={11} />} {k.delta} vs previous period
                      </div>
                    </div>
                  </div>
                ))}
              </div>

              <div className="gd-panels">
                <div className="gd-panel">
                  <div className="gd-panel-head">
                    <span className="gd-panel-title">Service Trend — This Week</span>
                    <span className="gd-panel-sub">JOBS / REVENUE (RS '000)</span>
                  </div>
                  <ResponsiveContainer width="100%" height={200}>
                    <AreaChart data={trend} margin={{ left: -20, right: 10 }}>
                      <defs>
                        <linearGradient id="jobsFill" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="0%" stopColor="#3C5A85" stopOpacity={0.55} />
                          <stop offset="100%" stopColor="#3C5A85" stopOpacity={0} />
                        </linearGradient>
                        <linearGradient id="revFill" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="0%" stopColor="#F0862F" stopOpacity={0.45} />
                          <stop offset="100%" stopColor="#F0862F" stopOpacity={0} />
                        </linearGradient>
                      </defs>
                      <CartesianGrid stroke="#E2E4E9" strokeDasharray="3 3" vertical={false} />
                      <XAxis dataKey="day" tick={{ fill: "#6B7280", fontSize: 10.5, fontFamily: "IBM Plex Mono" }} axisLine={{ stroke: "#E2E4E9" }} tickLine={false} />
                      <YAxis tick={{ fill: "#6B7280", fontSize: 10.5, fontFamily: "IBM Plex Mono" }} axisLine={false} tickLine={false} />
                      <Tooltip contentStyle={{ background: "#FFFFFF", border: "1px solid #E2E4E9", borderRadius: 6, fontSize: 12 }} labelStyle={{ color: "#16181C" }} />
                      <Area type="monotone" dataKey="jobs" stroke="#3C5A85" strokeWidth={2} fill="url(#jobsFill)" />
                      <Area type="monotone" dataKey="revenue" stroke="#F0862F" strokeWidth={2} fill="url(#revFill)" />
                    </AreaChart>
                  </ResponsiveContainer>
                </div>

                <div className="gd-panel">
                  <div className="gd-panel-head">
                    <span className="gd-panel-title">Jobs by Status</span>
                  </div>
                  <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
                    <ResponsiveContainer width={110} height={110}>
                      <PieChart>
                        <Pie data={STATUS} dataKey="value" nameKey="label" innerRadius={32} outerRadius={52} paddingAngle={2}>
                          {STATUS.map((s) => <Cell key={s.label} style={{ fill: s.color }} />)}
                        </Pie>
                      </PieChart>
                    </ResponsiveContainer>
                    <div className="gd-status-list" style={{ flex: 1 }}>
                      {STATUS.map((s) => (
                        <div className="gd-status-block" key={s.label}>
                          <div className="gd-status-row">
                            <span className="gd-status-dot" style={{ background: s.color }} />
                            <span className="gd-status-name">{s.label}</span>
                            <span className="gd-status-num">{s.value} <span style={{ color: "var(--text-dim)" }}>({s.pct}%)</span></span>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>

              <div className="gd-panel" style={{ marginBottom: 16 }}>
                <div className="gd-panel-head">
                  <span className="gd-panel-title">Revenue This Week</span>
                  <span className="gd-panel-sub">RS '000 PER DAY</span>
                </div>
                <ResponsiveContainer width="100%" height={160}>
                  <BarChart data={trend} margin={{ left: -20, right: 10 }}>
                    <CartesianGrid stroke="#E2E4E9" strokeDasharray="3 3" vertical={false} />
                    <XAxis dataKey="day" tick={{ fill: "#6B7280", fontSize: 10.5, fontFamily: "IBM Plex Mono" }} axisLine={{ stroke: "#E2E4E9" }} tickLine={false} />
                    <YAxis tick={{ fill: "#6B7280", fontSize: 10.5, fontFamily: "IBM Plex Mono" }} axisLine={false} tickLine={false} />
                    <Tooltip contentStyle={{ background: "#FFFFFF", border: "1px solid #E2E4E9", borderRadius: 6, fontSize: 12 }} labelStyle={{ color: "#16181C" }} />
                    <Bar dataKey="revenue" fill="#F0862F" radius={[4, 4, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
                <div style={{ fontSize: 12.5, color: "var(--text-dim)", marginTop: 8 }}>
                  Total revenue this period: <b style={{ color: "var(--text)", fontFamily: "IBM Plex Mono, monospace" }}>Rs {trend.reduce((s, t) => s + t.revenue, 0) * 1000}</b>
                </div>
              </div>

              <div className="gd-lower">
                <div className="gd-panel">
                  <div className="gd-panel-head">
                    <span className="gd-panel-title">Top Service Categories</span>
                    <span className="gd-panel-sub">128 JOBS</span>
                  </div>
                  {CATEGORIES.map((c) => (
                    <div className="gd-cat-row" key={c.name}>
                      <span className="gd-cat-name">{c.name}</span>
                      <div className="gd-cat-track"><div className="gd-cat-fill" style={{ width: c.pct + "%" }} /></div>
                      <span className="gd-cat-val">{c.value} ({c.pct}%)</span>
                    </div>
                  ))}
                </div>

                <div className="gd-panel">
                  <div className="gd-panel-head">
                    <span className="gd-panel-title">Mechanic Performance</span>
                  </div>
                  {MECHANICS.map((m) => (
                    <div className="gd-mech-row" key={m.name}>
                      <div className="gd-mech-avatar">{m.name.split(" ").map(w => w[0]).join("").slice(0,2)}</div>
                      <span className="gd-mech-name">{m.name}</span>
                      <span className="gd-mech-stat">{m.completed}✓</span>
                      <span className="gd-mech-stat">{m.pending}⧗</span>
                      <span className="gd-mech-rating">★ {m.rating}</span>
                    </div>
                  ))}
                  <div className="gd-view-all">View All Mechanics <ChevronRight size={13} /></div>
                </div>
              </div>

              <div className="gd-ticket-panel">
                <div className="gd-ticket-head">
                  <span className="gd-panel-title">Recent Generated Reports</span>
                  <span className="gd-panel-sub">WORK ORDER LOG</span>
                </div>
                {REPORTS.map((r) => (
                  <div className="gd-ticket-row" key={r.id}>
                    <span className="gd-ticket-id">{r.id}</span>
                    <span className="gd-ticket-name">{r.name}</span>
                    <span className="gd-ticket-type">{r.type}</span>
                    <span className="gd-ticket-cell">{r.range}</span>
                    <span className="gd-ticket-cell">{r.by}</span>
                    <span className="gd-ticket-fmt">{r.fmt}</span>
                    <span className="gd-ticket-actions"><Download size={14} /><Eye size={14} /><Trash2 size={14} /></span>
                  </div>
                ))}
                <div className="gd-view-all">View All Reports <ArrowRight size={13} /></div>
              </div>
            </div>

            <div className="gd-side">
              <div className="gd-form-panel">
                <div className="gd-form-title gd-display" style={{ textTransform: "none", letterSpacing: 0 }}>Generate Report</div>

                <div className="gd-field">
                  <div className="gd-field-label"><FileText size={12} /> Report Type</div>
                  <div className="gd-select-wrap">
                    <select><option>Select report type</option><option>Jobs Completed</option><option>Revenue Summary</option><option>Mechanic Performance</option><option>Inventory Usage</option></select>
                    <ChevronDown size={13} />
                  </div>
                </div>

                <div className="gd-field">
                  <div className="gd-field-label"><Calendar size={12} /> Date Range</div>
                  <div className="gd-range" style={{ width: "100%" }}>
                    <Calendar size={13} />
                    <input type="date" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} max={dateTo} />
                    <span className="gd-range-sep">–</span>
                    <input type="date" value={dateTo} onChange={(e) => setDateTo(e.target.value)} min={dateFrom} />
                  </div>
                </div>

                <div className="gd-field">
                  <div className="gd-field-label"><Layers size={12} /> Group By</div>
                  <div className="gd-select-wrap">
                    <select><option>Select group by</option><option>Day</option><option>Mechanic</option><option>Service Type</option><option>Branch</option></select>
                    <ChevronDown size={13} />
                  </div>
                </div>

                <div className="gd-field">
                  <div className="gd-field-label"><Filter size={12} /> Filters</div>
                  <div className="gd-field-row">
                    <div className="gd-select-wrap">
                      <select><option>All Services</option><option>Brake Repair</option><option>Engine Repair</option><option>AC Service</option></select>
                      <ChevronDown size={13} />
                    </div>
                    <div className="gd-select-wrap">
                      <select><option>All Mechanics</option>{MECHANICS.map((m) => <option key={m.name}>{m.name}</option>)}</select>
                      <ChevronDown size={13} />
                    </div>
                  </div>
                </div>

                <div className="gd-field" style={{ marginBottom: 18 }}>
                  <div className="gd-field-label">Status</div>
                  <div className="gd-select-wrap">
                    <select><option>All Status</option>{STATUS.map((s) => <option key={s.label}>{s.label}</option>)}</select>
                    <ChevronDown size={13} />
                  </div>
                </div>

                <button className="gd-btn-primary" onClick={handleCsv}><FileBarChart size={15} /> Generate Report</button>
                <button className="gd-btn-outline"><Repeat2 size={15} /> Schedule Report</button>
              </div>
            </div>
          </div>
        </div>
      </main>
    
  );
}