import { useState, useMemo } from "react";
import {
  Gauge, Wrench, Car, Users, Package, ClipboardList, Settings, LifeBuoy,
  Search, Bell, ChevronDown, Download, Eye, Trash2, ArrowUp, ArrowDown,
  Calendar, FileDown, ArrowRight, ChevronRight, PlusCircle, FileBarChart,
  FileText, Filter, Repeat2, Layers
} from "lucide-react";
import {
  AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  BarChart, Bar, PieChart, Pie, Cell
} from "recharts";

/* ---------------- data ---------------- */

const STATUS = [
  { label: "Completed", value: 82, pct: 64.1, color: "var(--green)" },
  { label: "In Progress", value: 28, pct: 21.9, color: "var(--steel-light)" },
  { label: "Pending", value: 34, pct: 26.6, color: "var(--amber)" },
  { label: "Waiting Parts", value: 12, pct: 9.4, color: "var(--rust)" },
  { label: "Cancelled", value: 4, pct: 3.1, color: "var(--red)" },
];

const CATEGORIES = [
  { name: "General Service", value: 45, pct: 35.2 },
  { name: "Brake Repair", value: 28, pct: 21.9 },
  { name: "Engine Repair", value: 22, pct: 17.2 },
  { name: "AC Service", value: 18, pct: 14.1 },
  { name: "Oil Change", value: 13, pct: 10.2 },
];

const MECHANICS = [
  { name: "Kasun Silva", completed: 18, pending: 4, rating: 4.8 },
  { name: "Nimal Fernando", completed: 15, pending: 3, rating: 4.6 },
  { name: "Priyantha", completed: 14, pending: 5, rating: 4.5 },
  { name: "Nalinda", completed: 12, pending: 2, rating: 4.3 },
  { name: "Chaminda", completed: 8, pending: 4, rating: 4.1 },
];

const REPORTS = [
  { id: "WO-2201", name: "Daily Service Report", type: "Daily", range: "May 27, 2025", by: "John Perera", fmt: "PDF" },
  { id: "WO-2198", name: "Weekly Performance Report", type: "Weekly", range: "May 20 – 27, 2025", by: "John Perera", fmt: "PDF" },
  { id: "WO-2190", name: "Mechanic Performance Report", type: "Mechanic", range: "May 01 – 27, 2025", by: "John Perera", fmt: "XLS" },
  { id: "WO-2187", name: "Monthly Revenue Report", type: "Financial", range: "May 01 – 27, 2025", by: "John Perera", fmt: "PDF" },
  { id: "WO-2179", name: "Service Summary Report", type: "Service", range: "May 20 – 27, 2025", by: "John Perera", fmt: "PDF" },
];

const NAV = [
  { icon: Car, label: "Assigned Vehicles", active: true },
  { icon: PlusCircle, label: "Add Vehicle" },
  { icon: FileBarChart, label: "Report Generation" },
  { icon: Calendar, label: "Calendar" },
];

/* ---------------- helpers ---------------- */

// Deterministic pseudo-random number from a string seed, so the same date
// always produces the same value (stands in for a real jobs/revenue API).
function seededValue(seed, min, max) {
  let hash = 0;
  for (let i = 0; i < seed.length; i++) hash = (hash * 31 + seed.charCodeAt(i)) >>> 0;
  return min + (hash % (max - min + 1));
}

const DAY_LABELS = ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"];

function generateTrend(fromStr, toStr) {
  const from = new Date(fromStr);
  const to = new Date(toStr);
  if (isNaN(from) || isNaN(to) || from > to) return [];
  const out = [];
  const cursor = new Date(from);
  let guard = 0;
  while (cursor <= to && guard < 31) {
    const iso = cursor.toISOString().slice(0, 10);
    out.push({
      date: iso,
      day: DAY_LABELS[cursor.getDay()] + " " + cursor.getDate(),
      jobs: seededValue(iso + "j", 4, 28),
      revenue: seededValue(iso + "r", 20, 130),
    });
    cursor.setDate(cursor.getDate() + 1);
    guard++;
  }
  return out;
}

function downloadCSV(trend, kpis, reports) {
  const lines = [
    ["AutoCare Garage - Supervisor Report"],
    [],
    ["Metric", "Value"],
    ...kpis.map((k) => [k.label, k.value]),
    [],
    ["Day", "Jobs", "Revenue (Rs '000)"],
    ...trend.map((t) => [t.day, t.jobs, t.revenue]),
    [],
    ["Report ID", "Name", "Type", "Date Range", "Generated By", "Format"],
    ...reports.map((r) => [r.id, r.name, r.type, r.range, r.by, r.fmt]),
  ];
  const csv = lines.map((row) => row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(",")).join("\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "autocare-dashboard.csv";
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

/* ---------------- styles ---------------- */

function Styles() {
  return (
    <style>{`
      @import url('https://fonts.googleapis.com/css2?family=Oswald:wght@500;600;700&family=IBM+Plex+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500;600&display=swap');

      .gd-root {
        --graphite: #FFFFFF;
        --panel: #FFFFFF;
        --panel-alt: #F1F2F5;
        --line: #E2E4E9;
        --amber: #F0862F;
        --amber-deep: #C96A1E;
        --steel: #10233F;
        --steel-light: #3C5A85;
        --rust: #B5654A;
        --green: #5FAE72;
        --red: #DD5E4E;
        --text: #16181C;
        --text-dim: #6B7280;
        font-family: 'IBM Plex Sans', sans-serif;
        background: var(--graphite);
        color: var(--text);
        min-height: 100%;
        width: 100%;
        display: flex;
      }
      .gd-root * { box-sizing: border-box; }
      .gd-display { font-family: 'Oswald', sans-serif; text-transform: uppercase; letter-spacing: 0.04em; }
      .gd-mono { font-family: 'IBM Plex Mono', monospace; }

      /* ---- sidebar ---- */
      .gd-sidebar { width: 232px; flex-shrink: 0; background: var(--steel); border-right: 1px solid var(--line); display: flex; flex-direction: column; padding: 20px 14px; }
      .gd-brand { display: flex; align-items: center; gap: 10px; padding: 4px 6px 22px; border-bottom: 1px solid var(--line); margin-bottom: 18px; }
      .gd-brand-mark { width: 34px; height: 34px; border-radius: 4px; background: var(--amber); display: flex; align-items: center; justify-content: center; color: #17181B; flex-shrink: 0; }
      .gd-brand-name { font-size: 15px; font-weight: 700; line-height: 1.1; }
      .gd-brand-sub { font-size: 9.5px; color: var(--text-dim); font-family: 'IBM Plex Mono', monospace; letter-spacing: 0.06em; margin-top: 2px; }

      .gd-nav-label { font-size: 10px; color: var(--text-dim); font-family: 'IBM Plex Mono', monospace; letter-spacing: 0.1em; padding: 4px 10px; margin-top: 4px; }
      .gd-nav-item { display: flex; align-items: center; gap: 13px; padding: 13px 14px; border-radius: 10px; color: #A9B4C4; font-family: 'IBM Plex Sans', sans-serif; font-size: 14.5px; font-weight: 700; cursor: pointer; margin-bottom: 6px; }
      .gd-nav-item:hover { color: var(--text); background: var(--panel-alt); }
      .gd-nav-item.active { color: #fff; background: var(--amber); }
      .gd-nav-item.active svg { color: #fff; }

      .gd-shift-card { margin-top: auto; background: var(--panel); border: 1px solid var(--line); border-radius: 8px; padding: 13px; }
      .gd-shift-head { font-size: 10px; font-family: 'IBM Plex Mono', monospace; color: var(--amber); letter-spacing: 0.08em; margin-bottom: 9px; }
      .gd-shift-row { display: flex; justify-content: space-between; font-size: 12px; padding: 4px 0; color: var(--text-dim); }
      .gd-shift-row b { color: var(--text); font-family: 'IBM Plex Mono', monospace; font-weight: 500; }

      /* ---- main ---- */
      .gd-main { flex: 1; min-width: 0; display: flex; flex-direction: column; }
      .gd-topbar { display: flex; align-items: center; justify-content: space-between; padding: 16px 28px; border-bottom: 1px solid var(--line); }
      .gd-crumb { font-size: 10.5px; color: var(--text-dim); font-family: 'IBM Plex Mono', monospace; letter-spacing: 0.06em; margin-bottom: 4px; }
      .gd-title { font-size: 21px; font-weight: 600; }
      .gd-top-right { display: flex; align-items: center; gap: 18px; }
      .gd-icon-btn { position: relative; background: none; border: none; color: var(--text-dim); cursor: pointer; }
      .gd-icon-btn:hover { color: var(--text); }
      .gd-dot { position: absolute; top: -3px; right: -3px; width: 7px; height: 7px; border-radius: 50%; background: var(--amber); border: 1.5px solid #FFFFFF; }
      .gd-user { display: flex; align-items: center; gap: 9px; padding-left: 16px; border-left: 1px solid var(--line); }
      .gd-user-avatar { width: 30px; height: 30px; border-radius: 50%; background: var(--amber); color: #17181B; display: flex; align-items: center; justify-content: center; font-weight: 700; font-size: 12px; font-family: 'Oswald', sans-serif; }
      .gd-user-name { font-size: 12.5px; font-weight: 600; line-height: 1.2; }
      .gd-user-role { font-size: 10.5px; color: var(--text-dim); }

      .gd-body { padding: 22px 28px 40px; }

      .gd-toolbar { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
      .gd-range { display: flex; align-items: center; gap: 8px; background: var(--panel); border: 1px solid var(--line); border-radius: 6px; padding: 7px 14px; font-size: 12.5px; color: var(--text-dim); font-family: 'IBM Plex Mono', monospace; }
      .gd-range input[type="date"] { background: transparent; border: none; color: var(--text); font-family: 'IBM Plex Mono', monospace; font-size: 12.5px; padding: 2px 0; }
      .gd-range input[type="date"]::-webkit-calendar-picker-indicator { filter: invert(0.8); cursor: pointer; }
      .gd-range span.gd-range-sep { color: var(--text-dim); }
      .gd-export-wrap { position: relative; }
      .gd-export { display: flex; align-items: center; gap: 8px; background: var(--amber); color: #1B1500; border: none; border-radius: 6px; padding: 9px 16px; font-size: 12.5px; font-weight: 600; cursor: pointer; }
      .gd-export:hover { background: var(--amber-deep); }
      .gd-export-menu { position: absolute; right: 0; top: calc(100% + 6px); background: var(--panel); border: 1px solid var(--line); border-radius: 8px; overflow: hidden; min-width: 190px; box-shadow: 0 8px 24px rgba(0,0,0,0.4); z-index: 10; }
      .gd-export-item { display: flex; align-items: center; gap: 9px; padding: 11px 14px; font-size: 12.5px; color: var(--text); cursor: pointer; }
      .gd-export-item:hover { background: var(--panel-alt); color: var(--amber); }

      @media print {
        .gd-sidebar, .gd-icon-btn, .gd-export-wrap, .gd-ticket-actions, .gd-view-all, .gd-side { display: none !important; }
        .gd-layout { grid-template-columns: 1fr !important; }
        .gd-root, .gd-main { background: #fff !important; color: #111 !important; }
        .gd-panel, .gd-ticket-panel, .gd-gauge-card { background: #fff !important; border: 1px solid #ccc !important; }
        .gd-topbar { border-bottom: 1px solid #ccc !important; }
      }

      /* ---- gauges ---- */
      .gd-gauges { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-bottom: 18px; }
      .gd-gauge-card { background: var(--panel); border: 1px solid var(--line); border-radius: 10px; padding: 18px; display: flex; align-items: center; gap: 16px; box-shadow: 0 1px 3px rgba(16,35,63,0.06); }
      .gd-gauge-ring { width: 68px; height: 68px; border-radius: 50%; display: flex; align-items: center; justify-content: center; flex-shrink: 0; position: relative; }
      .gd-gauge-ring::before { content: ''; position: absolute; inset: 7px; border-radius: 50%; background: var(--panel); }
      .gd-gauge-val { position: relative; font-family: 'IBM Plex Mono', monospace; font-size: 13px; font-weight: 600; z-index: 1; }
      .gd-gauge-label { font-size: 11px; color: var(--text-dim); margin-bottom: 4px; letter-spacing: 0.03em; }
      .gd-gauge-num { font-family: 'Oswald', sans-serif; font-size: 22px; font-weight: 600; }
      .gd-gauge-delta { display: flex; align-items: center; gap: 3px; font-size: 11px; margin-top: 3px; font-family: 'IBM Plex Mono', monospace; }
      .gd-up { color: var(--green); } .gd-down { color: var(--red); }

      /* ---- panels ---- */
      .gd-panels { display: grid; grid-template-columns: 1.5fr 1fr; gap: 16px; margin-bottom: 16px; }
      .gd-panel { background: var(--panel); border: 1px solid var(--line); border-radius: 10px; padding: 20px; box-shadow: 0 1px 3px rgba(16,35,63,0.06); }
      .gd-panel-head { display: flex; justify-content: space-between; align-items: baseline; margin-bottom: 16px; }
      .gd-panel-title { font-size: 13px; font-weight: 600; }
      .gd-panel-sub { font-size: 10.5px; color: var(--text-dim); font-family: 'IBM Plex Mono', monospace; }

      .gd-status-list { display: flex; flex-direction: column; gap: 10px; margin-top: 4px; }
      .gd-status-row { display: flex; align-items: center; gap: 10px; }
      .gd-status-dot { width: 9px; height: 9px; border-radius: 2px; flex-shrink: 0; }
      .gd-status-name { flex: 1; font-size: 12.5px; color: var(--text-dim); }
      .gd-status-num { font-family: 'IBM Plex Mono', monospace; font-size: 12px; }
      .gd-status-track { width: 100%; height: 4px; background: var(--panel-alt); border-radius: 2px; margin-top: 5px; overflow: hidden; }
      .gd-status-fill { height: 100%; border-radius: 2px; }
      .gd-status-block { margin-bottom: 2px; }

      .gd-lower { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 16px; }

      .gd-cat-row { display: grid; grid-template-columns: 110px 1fr 70px; align-items: center; gap: 10px; margin-bottom: 11px; }
      .gd-cat-name { font-size: 12px; color: var(--text-dim); }
      .gd-cat-track { height: 8px; background: var(--panel-alt); border-radius: 4px; overflow: hidden; }
      .gd-cat-fill { height: 100%; background: linear-gradient(90deg, var(--amber-deep), var(--amber)); border-radius: 4px; }
      .gd-cat-val { font-family: 'IBM Plex Mono', monospace; font-size: 11.5px; text-align: right; color: var(--text-dim); }

      .gd-mech-row { display: flex; align-items: center; gap: 10px; padding: 8px 0; border-bottom: 1px solid var(--line); }
      .gd-mech-row:last-child { border-bottom: none; }
      .gd-mech-avatar { width: 26px; height: 26px; border-radius: 50%; background: var(--panel-alt); border: 1px solid var(--line); display: flex; align-items: center; justify-content: center; font-size: 10px; font-weight: 600; font-family: 'Oswald', sans-serif; color: var(--amber); flex-shrink: 0; }
      .gd-mech-name { flex: 1; font-size: 12.5px; }
      .gd-mech-stat { font-family: 'IBM Plex Mono', monospace; font-size: 11.5px; color: var(--text-dim); width: 30px; text-align: center; }
      .gd-mech-rating { font-family: 'IBM Plex Mono', monospace; font-size: 11.5px; color: var(--amber); width: 34px; text-align: right; }

      /* ---- ticket table ---- */
      .gd-ticket-panel { background: var(--panel); border: 1px solid var(--line); border-radius: 10px; overflow: hidden; box-shadow: 0 1px 3px rgba(16,35,63,0.06); }
      .gd-ticket-head { display: flex; justify-content: space-between; align-items: center; padding: 18px 20px 14px; }
      .gd-ticket-row { display: grid; grid-template-columns: 90px 1.6fr 90px 1.4fr 1fr 60px 70px; align-items: center; gap: 10px; padding: 12px 20px; position: relative; border-top: 1px dashed var(--line); }
      .gd-ticket-row::before, .gd-ticket-row::after { content: ''; position: absolute; width: 12px; height: 12px; border-radius: 50%; background: var(--graphite); top: -7px; }
      .gd-ticket-row::before { left: -6px; } .gd-ticket-row::after { right: -6px; }
      .gd-ticket-id { font-family: 'IBM Plex Mono', monospace; font-size: 11.5px; color: var(--amber); }
      .gd-ticket-name { font-size: 12.5px; font-weight: 500; }
      .gd-ticket-type { font-size: 11px; color: var(--text-dim); background: var(--panel-alt); padding: 3px 8px; border-radius: 20px; display: inline-block; width: fit-content; }
      .gd-ticket-cell { font-size: 12px; color: var(--text-dim); font-family: 'IBM Plex Mono', monospace; }
      .gd-ticket-fmt { font-size: 10.5px; font-weight: 600; color: var(--steel); }
      .gd-ticket-actions { display: flex; gap: 10px; color: var(--text-dim); }
      .gd-ticket-actions svg:hover { color: var(--amber); cursor: pointer; }
      .gd-view-all { display: flex; align-items: center; justify-content: center; gap: 6px; padding: 13px; font-size: 12px; color: var(--amber); border-top: 1px solid var(--line); cursor: pointer; }

      /* ---- right column layout ---- */
      .gd-layout { display: grid; grid-template-columns: 1fr 300px; gap: 16px; align-items: start; }
      .gd-content { min-width: 0; }
      .gd-side { display: flex; flex-direction: column; gap: 16px; }

      /* ---- generate report form ---- */
      .gd-form-panel { background: var(--panel); border: 1px solid var(--line); border-radius: 10px; padding: 20px; box-shadow: 0 1px 3px rgba(16,35,63,0.06); }
      .gd-form-title { font-size: 15px; font-weight: 700; margin-bottom: 16px; }
      .gd-field { margin-bottom: 14px; }
      .gd-field-label { font-size: 11px; color: var(--text-dim); font-weight: 600; letter-spacing: 0.02em; margin-bottom: 6px; display: flex; align-items: center; gap: 6px; }
      .gd-select-wrap { position: relative; }
      .gd-select-wrap select { width: 100%; appearance: none; background: var(--panel-alt); border: 1px solid var(--line); border-radius: 7px; padding: 9px 30px 9px 10px; font-size: 12.5px; color: var(--text); font-family: 'IBM Plex Sans', sans-serif; }
      .gd-select-wrap svg { position: absolute; right: 9px; top: 10px; color: var(--text-dim); pointer-events: none; }
      .gd-field-row { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }
      .gd-btn-primary { width: 100%; background: var(--amber); color: #fff; border: none; border-radius: 7px; padding: 11px; font-size: 13px; font-weight: 700; cursor: pointer; display: flex; align-items: center; justify-content: center; gap: 7px; margin-bottom: 9px; }
      .gd-btn-primary:hover { background: var(--amber-deep); }
      .gd-btn-outline { width: 100%; background: transparent; color: var(--steel); border: 1px solid var(--line); border-radius: 7px; padding: 11px; font-size: 13px; font-weight: 700; cursor: pointer; display: flex; align-items: center; justify-content: center; gap: 7px; }
      .gd-btn-outline:hover { border-color: var(--steel); }

      /* ---- report shortcuts ---- */
      /* ---- report shortcuts (removed from UI, styles kept minimal) ---- */
    `}</style>
  );
}

/* ---------------- gauge helper ---------------- */

function Gauge_({ pct, color, value, delta, positive }) {
  const bg = `conic-gradient(${color} ${pct * 3.6}deg, var(--panel-alt) 0deg)`;
  return (
    <div className="gd-gauge-ring" style={{ background: bg }}>
      <span className="gd-gauge-val">{pct}%</span>
    </div>
  );
}

/* ---------------- app ---------------- */

export default function App() {
  const [dateFrom, setDateFrom] = useState("2025-05-20");
  const [dateTo, setDateTo] = useState("2025-05-27");
  const [exportOpen, setExportOpen] = useState(false);

  const trend = useMemo(() => generateTrend(dateFrom, dateTo), [dateFrom, dateTo]);

  const kpis = useMemo(() => {
    const totalJobs = trend.reduce((s, t) => s + t.jobs, 0) || 1;
    const completed = Math.round(totalJobs * 0.64);
    const pending = Math.round(totalJobs * 0.27);
    const customers = Math.round(totalJobs * 0.75);
    return [
      { label: "Total Jobs", value: String(totalJobs), pct: 100, color: "var(--steel-light)", delta: "+12.5%", positive: true },
      { label: "Completed", value: String(completed), pct: Math.round((completed / totalJobs) * 100), color: "var(--green)", delta: "+18.3%", positive: true },
      { label: "Pending", value: String(pending), pct: Math.round((pending / totalJobs) * 100), color: "var(--amber)", delta: "-6.7%", positive: false },
      { label: "Customers", value: String(customers), pct: 78, color: "var(--rust)", delta: "+15.7%", positive: true },
    ];
  }, [trend]);

  const handlePrint = () => {
    setExportOpen(false);
    window.print();
  };
  const handleCsv = () => {
    setExportOpen(false);
    downloadCSV(trend, kpis, REPORTS);
  };

  return (
    <div className="gd-root">
      <Styles />

      <div className="gd-sidebar">
        <div className="gd-brand">
          <div className="gd-brand-mark"><Wrench size={18} /></div>
          <div>
            <div className="gd-brand-name gd-display">AutoCare</div>
            <div className="gd-brand-sub">GARAGE MGMT · BAY 04</div>
          </div>
        </div>

        <div className="gd-nav-label">MAIN MENU</div>
        {NAV.map((n) => (
          <div key={n.label} className={"gd-nav-item" + (n.active ? " active" : "")}>
            <n.icon size={19} /> {n.label}
          </div>
        ))}

        <div className="gd-shift-card">
          <div className="gd-shift-head">TODAY'S SHIFT · 10:30</div>
          <div className="gd-shift-row"><span>Jobs Completed</span><b>16</b></div>
          <div className="gd-shift-row"><span>Revenue</span><b>Rs 125,750</b></div>
          <div className="gd-shift-row"><span>New Customers</span><b>8</b></div>
          <div className="gd-shift-row"><span>Approvals Due</span><b>5</b></div>
        </div>
      </div>

      <div className="gd-main">
        <div className="gd-topbar">
          <div>
            <div className="gd-crumb">REPORTS / DASHBOARD</div>
            <div className="gd-title gd-display">Supervisor Report</div>
          </div>
          <div className="gd-top-right">
            <button className="gd-icon-btn"><Search size={17} /></button>
            <button className="gd-icon-btn"><Bell size={17} /><span className="gd-dot" /></button>
            <div className="gd-user">
              <div className="gd-user-avatar">JP</div>
              <div>
                <div className="gd-user-name">John Perera</div>
                <div className="gd-user-role">Supervisor</div>
              </div>
            </div>
          </div>
        </div>

        <div className="gd-body">
          <div className="gd-toolbar">
            <div className="gd-range">
              <Calendar size={13} />
              <input type="date" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} max={dateTo} />
              <span className="gd-range-sep">–</span>
              <input type="date" value={dateTo} onChange={(e) => setDateTo(e.target.value)} min={dateFrom} />
            </div>
            <div className="gd-export-wrap">
              <button className="gd-export" onClick={() => setExportOpen((v) => !v)}>
                <FileDown size={14} /> Export Dashboard <ChevronDown size={13} />
              </button>
              {exportOpen && (
                <div className="gd-export-menu">
                  <div className="gd-export-item" onClick={handlePrint}><FileDown size={14} /> Export as PDF</div>
                  <div className="gd-export-item" onClick={handleCsv}><Download size={14} /> Export as CSV</div>
                </div>
              )}
            </div>
          </div>

          <div className="gd-layout">
            <div className="gd-content">
              {/* gauges */}
              <div className="gd-gauges">
                {kpis.map((k) => (
                  <div className="gd-gauge-card" key={k.label}>
                    <Gauge_ {...k} />
                    <div>
                      <div className="gd-gauge-label">{k.label}</div>
                      <div className="gd-gauge-num gd-mono">{k.value}</div>
                      <div className={"gd-gauge-delta " + (k.positive ? "gd-up" : "gd-down")}>
                        {k.positive ? <ArrowUp size={11} /> : <ArrowDown size={11} />} {k.delta} vs previous period
                      </div>
                    </div>
                  </div>
                ))}
              </div>

              {/* trend + status */}
              <div className="gd-panels">
                <div className="gd-panel">
                  <div className="gd-panel-head">
                    <span className="gd-panel-title">Service Trend — This Week</span>
                    <span className="gd-panel-sub">JOBS / REVENUE (RS '000)</span>
                  </div>
                  <ResponsiveContainer width="100%" height={200}>
                    <AreaChart data={trend} margin={{ left: -20, right: 10 }}>
                      <defs>
                        <linearGradient id="jobsFill" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="0%" stopColor="#3C5A85" stopOpacity={0.55} />
                          <stop offset="100%" stopColor="#3C5A85" stopOpacity={0} />
                        </linearGradient>
                        <linearGradient id="revFill" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="0%" stopColor="#F0862F" stopOpacity={0.45} />
                          <stop offset="100%" stopColor="#F0862F" stopOpacity={0} />
                        </linearGradient>
                      </defs>
                      <CartesianGrid stroke="#E2E4E9" strokeDasharray="3 3" vertical={false} />
                      <XAxis dataKey="day" tick={{ fill: "#6B7280", fontSize: 10.5, fontFamily: "IBM Plex Mono" }} axisLine={{ stroke: "#E2E4E9" }} tickLine={false} />
                      <YAxis tick={{ fill: "#6B7280", fontSize: 10.5, fontFamily: "IBM Plex Mono" }} axisLine={false} tickLine={false} />
                      <Tooltip contentStyle={{ background: "#FFFFFF", border: "1px solid #E2E4E9", borderRadius: 6, fontSize: 12 }} labelStyle={{ color: "#16181C" }} />
                      <Area type="monotone" dataKey="jobs" stroke="#3C5A85" strokeWidth={2} fill="url(#jobsFill)" />
                      <Area type="monotone" dataKey="revenue" stroke="#F0862F" strokeWidth={2} fill="url(#revFill)" />
                    </AreaChart>
                  </ResponsiveContainer>
                </div>

                <div className="gd-panel">
                  <div className="gd-panel-head">
                    <span className="gd-panel-title">Jobs by Status</span>
                  </div>
                  <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
                    <ResponsiveContainer width={110} height={110}>
                      <PieChart>
                        <Pie data={STATUS} dataKey="value" nameKey="label" innerRadius={32} outerRadius={52} paddingAngle={2}>
                          {STATUS.map((s) => <Cell key={s.label} style={{ fill: s.color }} />)}
                        </Pie>
                      </PieChart>
                    </ResponsiveContainer>
                    <div className="gd-status-list" style={{ flex: 1 }}>
                      {STATUS.map((s) => (
                        <div className="gd-status-block" key={s.label}>
                          <div className="gd-status-row">
                            <span className="gd-status-dot" style={{ background: s.color }} />
                            <span className="gd-status-name">{s.label}</span>
                            <span className="gd-status-num">{s.value} <span style={{ color: "var(--text-dim)" }}>({s.pct}%)</span></span>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>

              {/* revenue overview */}
              <div className="gd-panel" style={{ marginBottom: 16 }}>
                <div className="gd-panel-head">
                  <span className="gd-panel-title">Revenue This Week</span>
                  <span className="gd-panel-sub">RS '000 PER DAY</span>
                </div>
                <ResponsiveContainer width="100%" height={160}>
                  <BarChart data={trend} margin={{ left: -20, right: 10 }}>
                    <CartesianGrid stroke="#E2E4E9" strokeDasharray="3 3" vertical={false} />
                    <XAxis dataKey="day" tick={{ fill: "#6B7280", fontSize: 10.5, fontFamily: "IBM Plex Mono" }} axisLine={{ stroke: "#E2E4E9" }} tickLine={false} />
                    <YAxis tick={{ fill: "#6B7280", fontSize: 10.5, fontFamily: "IBM Plex Mono" }} axisLine={false} tickLine={false} />
                    <Tooltip contentStyle={{ background: "#FFFFFF", border: "1px solid #E2E4E9", borderRadius: 6, fontSize: 12 }} labelStyle={{ color: "#16181C" }} />
                    <Bar dataKey="revenue" fill="#F0862F" radius={[4, 4, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
                <div style={{ fontSize: 12.5, color: "var(--text-dim)", marginTop: 8 }}>
                  Total revenue this period: <b style={{ color: "var(--text)", fontFamily: "IBM Plex Mono, monospace" }}>Rs {trend.reduce((s, t) => s + t.revenue, 0) * 1000}</b>
                </div>
              </div>

              {/* categories + mechanics */}
              <div className="gd-lower">
                <div className="gd-panel">
                  <div className="gd-panel-head">
                    <span className="gd-panel-title">Top Service Categories</span>
                    <span className="gd-panel-sub">128 JOBS</span>
                  </div>
                  {CATEGORIES.map((c) => (
                    <div className="gd-cat-row" key={c.name}>
                      <span className="gd-cat-name">{c.name}</span>
                      <div className="gd-cat-track"><div className="gd-cat-fill" style={{ width: c.pct + "%" }} /></div>
                      <span className="gd-cat-val">{c.value} ({c.pct}%)</span>
                    </div>
                  ))}
                </div>

                <div className="gd-panel">
                  <div className="gd-panel-head">
                    <span className="gd-panel-title">Mechanic Performance</span>
                  </div>
                  {MECHANICS.map((m) => (
                    <div className="gd-mech-row" key={m.name}>
                      <div className="gd-mech-avatar">{m.name.split(" ").map(w => w[0]).join("").slice(0,2)}</div>
                      <span className="gd-mech-name">{m.name}</span>
                      <span className="gd-mech-stat">{m.completed}✓</span>
                      <span className="gd-mech-stat">{m.pending}⧗</span>
                      <span className="gd-mech-rating">★ {m.rating}</span>
                    </div>
                  ))}
                  <div className="gd-view-all">View All Mechanics <ChevronRight size={13} /></div>
                </div>
              </div>

              {/* reports ticket table */}
              <div className="gd-ticket-panel">
                <div className="gd-ticket-head">
                  <span className="gd-panel-title">Recent Generated Reports</span>
                  <span className="gd-panel-sub">WORK ORDER LOG</span>
                </div>
                {REPORTS.map((r) => (
                  <div className="gd-ticket-row" key={r.id}>
                    <span className="gd-ticket-id">{r.id}</span>
                    <span className="gd-ticket-name">{r.name}</span>
                    <span className="gd-ticket-type">{r.type}</span>
                    <span className="gd-ticket-cell">{r.range}</span>
                    <span className="gd-ticket-cell">{r.by}</span>
                    <span className="gd-ticket-fmt">{r.fmt}</span>
                    <span className="gd-ticket-actions"><Download size={14} /><Eye size={14} /><Trash2 size={14} /></span>
                  </div>
                ))}
                <div className="gd-view-all">View All Reports <ArrowRight size={13} /></div>
              </div>
            </div>

            <div className="gd-side">
              <div className="gd-form-panel">
                <div className="gd-form-title gd-display" style={{ textTransform: "none", letterSpacing: 0 }}>Generate Report</div>

                <div className="gd-field">
                  <div className="gd-field-label"><FileText size={12} /> Report Type</div>
                  <div className="gd-select-wrap">
                    <select><option>Select report type</option><option>Jobs Completed</option><option>Revenue Summary</option><option>Mechanic Performance</option><option>Inventory Usage</option></select>
                    <ChevronDown size={13} />
                  </div>
                </div>

                <div className="gd-field">
                  <div className="gd-field-label"><Calendar size={12} /> Date Range</div>
                  <div className="gd-range" style={{ width: "100%" }}>
                    <Calendar size={13} />
                    <input type="date" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} max={dateTo} />
                    <span className="gd-range-sep">–</span>
                    <input type="date" value={dateTo} onChange={(e) => setDateTo(e.target.value)} min={dateFrom} />
                  </div>
                </div>

                <div className="gd-field">
                  <div className="gd-field-label"><Layers size={12} /> Group By</div>
                  <div className="gd-select-wrap">
                    <select><option>Select group by</option><option>Day</option><option>Mechanic</option><option>Service Type</option><option>Branch</option></select>
                    <ChevronDown size={13} />
                  </div>
                </div>

                <div className="gd-field">
                  <div className="gd-field-label"><Filter size={12} /> Filters</div>
                  <div className="gd-field-row">
                    <div className="gd-select-wrap">
                      <select><option>All Services</option><option>Brake Repair</option><option>Engine Repair</option><option>AC Service</option></select>
                      <ChevronDown size={13} />
                    </div>
                    <div className="gd-select-wrap">
                      <select><option>All Mechanics</option>{MECHANICS.map((m) => <option key={m.name}>{m.name}</option>)}</select>
                      <ChevronDown size={13} />
                    </div>
                  </div>
                </div>

                <div className="gd-field" style={{ marginBottom: 18 }}>
                  <div className="gd-field-label">Status</div>
                  <div className="gd-select-wrap">
                    <select><option>All Status</option>{STATUS.map((s) => <option key={s.label}>{s.label}</option>)}</select>
                    <ChevronDown size={13} />
                  </div>
                </div>

                <button className="gd-btn-primary" onClick={handleCsv}><FileBarChart size={15} /> Generate Report</button>
                <button className="gd-btn-outline"><Repeat2 size={15} /> Schedule Report</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
